services:
  db:
    image: postgis/postgis:14-3.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=climateconnect_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 54321:5432
  redis:
    image: redis:6
    ports:
      - 6379:6379
  app:
    build: .
    command: sleep infinity
    working_dir: /workspace
    volumes:
      - .:/workspace
    ports:
      - 8000:8000
    environment:
      - DATABASE_NAME=climateconnect_db
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin
    depends_on:
      - db
      - redis
volumes:
  postgres_data: