name: Lint frontend
on: [pull_request]


jobs:
  build:
    defaults:
      run:
        working-directory: frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check out Git repository
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: yarn --immutable

      - name: Lint frontend
        run: yarn lint
      - name: Format-check frontend
        run: yarn format --check

      - name: Typescript Compile frontend
        run: yarn tsc